---
- name: Configure and deploy Nginx without Docker
  hosts: localhost
  become: true
  tasks:
    - name: Update apt and install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure /etc/nginx/sites-available directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Ensure /etc/nginx/sites-enabled directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Create a new Nginx configuration
      ansible.builtin.copy:
        content: |
          server {
              listen       443;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  index.html;
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }
          }
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart Nginx

    - name: Ensure the Nginx configuration is enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Ensure index.html exists
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Welcome to My Website!</title>
          </head>
          <body>
              <div style="text-align: center; padding: 50px;">
                  <h1>Welcome to My Website with flush handler!</h1>
                  <p>This page is served by Nginx.</p>
                  <p>You can see this page on your browser by visiting <strong>http://localhost</strong>.</p>
              </div>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
      notify: Restart Nginx

    - name: Flush handlers to apply new configuration immediately
      ansible.builtin.meta: flush_handlers

    - name: Pause for demonstration
      ansible.builtin.pause:
        seconds: 15

    - name: Verify the Nginx service is running
      ansible.builtin.systemd:
        name: nginx
        state: started
      register: service_status
      ignore_errors: true

    - name: Print service status
      ansible.builtin.debug:
        msg: "Service status: {{ service_status.status }}"

  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
