---
- name: Configure and deploy Nginx with enforced restart
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx Docker image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Create volume
      community.docker.docker_volume:
        name: nginx-data
        driver: local

    - name: Create Nginx container
      community.docker.docker_container:
        name: nginx_without_flush
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "nginx-data:/usr/share/nginx/html:ro"

    - name: Create a new Nginx configuration file locally
      ansible.builtin.copy:
        content: |
          server {
              listen       80;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  index.html;
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }
          }
        dest: /tmp/default.conf
        mode: '0644'

    - name: Create a new index.html file locally
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Welcome to My Website!</title>
          </head>
          <body>
              <div style="text-align: center; padding: 50px;">
                  <h1>Welcome to My Website with enforced restart!</h1>
                  <p>This page is served by Nginx.</p>
                  <p>You can see this page on your browser by visiting <strong>http://localhost</strong>.</p>
              </div>
          </body>
          </html>
        dest: /tmp/index.html
        mode: '0644'

    - name: Copy the new Nginx configuration into the container
      community.docker.docker_cp:
        src: /tmp/default.conf
        dest: /etc/nginx/conf.d/default.conf
        container: nginx_without_flush
      notify: Restart Nginx

    - name: Copy the new index.html into the container
      community.docker.docker_cp:
        src: /tmp/index.html
        dest: /usr/share/nginx/html/index.html
        container: nginx_without_flush
      notify: Restart Nginx

    - name: Pause for demonstration
      ansible.builtin.pause:
        seconds: 15

    - name: Verify the Nginx service is running
      ansible.builtin.command: docker ps --filter "name=nginx_with_restart"
      register: service_status
      ignore_errors: true

    - name: Print service status
      ansible.builtin.debug:
        msg: "Service status: {{ service_status.stdout }}"

  handlers:
    - name: Restart Nginx
      command: docker restart nginx_without_handler
