---
- name: Configure and deploy Nginx with enforced restart
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx Docker image
      community.docker.docker_image:
        name: nginx
        source: pull
        
    - name: Create Nginx container
      community.docker.docker_container:
        name: nginx_without_handler
        image: nginx
        state: started
        ports:
          - "80:80"
        #volumes:
        #  - /usr/share/nginx/html:/usr/share/nginx/html
        #  - /etc/nginx/conf.d:/etc/nginx/conf.d
          
    - name: Ensure /etc/nginx/conf.d directory exists on host
      ansible.builtin.file:
        path: /etc/nginx/conf.d
        state: directory

    - name: Ensure /usr/share/nginx/html directory exists on host
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Create a new Nginx configuration on host
      ansible.builtin.copy:
        content: |
          server {
              listen       80;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  init.html;
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }
          }
        dest: /etc/nginx/conf.d/init.conf
        mode: '0644'

    - name: Ensure index.html exists on host
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Welcome to My Website!</title>
          </head>
          <body>
              <div style="text-align: center; padding: 50px;">
                  <h1>Welcome to My Website without flush handler!</h1>
                  <p>This page is served by Nginx.</p>
                  <p>You can see this page on your browser by visiting <strong>http://localhost</strong>.</p>
              </div>
          </body>
          </html>
        dest: /usr/share/nginx/html/init.html
        mode: '0644'
        
    - name: Copy new Nginx configuration into the container using docker cp
      ansible.builtin.command:
        cmd: "docker cp /etc/nginx/conf.d/init.conf nginx_without_handler:/etc/nginx/conf.d/default.conf"
      notify: Restart Nginx

    - name: Copy new index.html into the container using docker cp
      ansible.builtin.command:
        cmd: "docker cp /usr/share/nginx/html/init.html nginx_without_handler:/usr/share/nginx/html/index.html"
      notify: Restart Nginx

    - name: Pause for demonstration
      ansible.builtin.pause:
        seconds: 15

    - name: Verify the Nginx service is running
      ansible.builtin.command: docker ps --filter "name=nginx_without_handler"
      register: service_status
      ignore_errors: true

    - name: Print service status
      ansible.builtin.debug:
        msg: "Service status: {{ service_status.stdout }}"

  handlers:
    - name: Restart Nginx
      ansible.builtin.command:
        cmd: docker restart nginx_without_handler
